language: php
php:
  - 5.4
  - 5.5
  - 5.6

before_script:
   - composer install

script: phpunit ./tests

notifications:
  email: false
  irc:
    channels:
       secure: "IL3HE1xWBVCaJMEQ6+7jE+K+EKJspfJAAgD8cIuvSbp75ANAzOGhTB8oKSiXhpqycdiT1g9DFw63aE/aP5v7hzR5KIioEi29ObWihY2xE5GgLlKEnSEw2TsikjPvmio7AuE3bLrFg8GBuZICcH5qG+qQzfAZInp1DSrk3VghmDc="
    on_success: change
    on_failure: always
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover


sudo: false
